In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\lapto\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lapto\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lapto\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lapto\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lapto\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\lapto\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import json

In [4]:
# Ruta de tu archivo
df = pd.read_csv('data.csv')

In [5]:
# Ver las primeras filas
df.head()

,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,liked
0,0.803,0.6240,7,-6.764,0,0.0477,0.451,0.000734,0.1000,0.6280,95.968,304524,4,0
1,0.762,0.7030,10,-7.951,0,0.3060,0.206,0.000000,0.0912,0.5190,151.329,247178,4,1
2,0.261,0.0149,1,-27.528,1,0.0419,0.992,0.897000,0.1020,0.0382,75.296,286987,4,0
3,0.722,0.7360,3,-6.994,0,0.0585,0.431,0.000001,0.1230,0.5820,89.860,208920,4,1
4,0.787,0.5720,1,-7.516,1,0.2220,0.145,0.000000,0.0753,0.6470,155.117,179413,4,1

In [6]:
# Ver información sobre las columnas y tipos de datos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   danceability      195 non-null    float64
 1   energy            195 non-null    float64
 2   key               195 non-null    int64
 3   loudness          195 non-null    float64
 4   mode              195 non-null    int64
 5   speechiness       195 non-null    float64
 6   acousticness      195 non-null    float64
 7   instrumentalness  195 non-null    float64
 8   liveness          195 non-null    float64
 9   valence           195 non-null    float64
 10  tempo             195 non-null    float64
 11  duration_ms       195 non-null    int64
 12  time_signature    195 non-null    int64
 13  liked             195 non-null    int64
dtypes: float64(9), int64(5)
memory usage: 21.5 KB

In [12]:
# Ver información general del DataFrame
print("Información del DataFrame:")
df.info()

Información del DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   danceability      195 non-null    float64
 1   energy            195 non-null    float64
 2   key               195 non-null    int64
 3   loudness          195 non-null    float64
 4   mode              195 non-null    int64
 5   speechiness       195 non-null    float64
 6   acousticness      195 non-null    float64
 7   instrumentalness  195 non-null    float64
 8   liveness          195 non-null    float64
 9   valence           195 non-null    float64
 10  tempo             195 non-null    float64
 11  duration_ms       195 non-null    int64
 12  time_signature    195 non-null    int64
 13  liked             195 non-null    int64
dtypes: float64(9), int64(5)
memory usage: 21.5 KB

In [7]:
# Ver estadísticas descriptivas
df.describe()

,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,liked
count,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000
mean,0.636656,0.638431,5.497436,-9.481631,0.538462,0.148957,0.319093,0.192337,0.148455,0.493632,121.086174,213408.933333,3.912821,0.512821
std,0.216614,0.260096,3.415209,6.525086,0.499802,0.120414,0.320782,0.346226,0.105975,0.267695,28.084829,72152.392864,0.451332,0.501122
min,0.130000,0.002400,0.000000,-42.261000,0.000000,0.027800,0.000003,0.000000,0.033100,0.035300,60.171000,77203.000000,1.000000,0.000000
25%,0.462500,0.533500,2.000000,-9.962000,0.000000,0.056800,0.042200,0.000000,0.084000,0.269000,100.242000,178300.500000,4.000000,0.000000
50%,0.705000,0.659000,6.000000,-7.766000,1.000000,0.096200,0.213000,0.000008,0.105000,0.525000,124.896000,204000.000000,4.000000,1.000000
75%,0.799000,0.837500,8.000000,-5.829000,1.000000,0.230500,0.504000,0.097500,0.177000,0.717500,142.460500,242373.500000,4.000000,1.000000
max,0.946000,0.996000,11.000000,-2.336000,1.000000,0.540000,0.995000,0.969000,0.633000,0.980000,180.036000,655213.000000,5.000000,1.000000

In [13]:
# Verificar valores nulos
print("\nValores nulos por columna:")
df.isnull().sum()

Valores nulos por columna:

danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
duration_ms         0
time_signature      0
liked               0
dtype: int64

In [14]:
# Convertir a JSON (formato orientado a registros)
json_data = df.to_json(orient='records', indent=2)

# Mostrar una parte del resultado
print(json_data[:500])  # Muestra los primeros 500 caracteres

[
  {
    "danceability":0.803,
    "energy":0.624,
    "key":7,
    "loudness":-6.764,
    "mode":0,
    "speechiness":0.0477,
    "acousticness":0.451,
    "instrumentalness":0.000734,
    "liveness":0.1,
    "valence":0.628,
    "tempo":95.968,
    "duration_ms":304524,
    "time_signature":4,
    "liked":0
  },
  {
    "danceability":0.762,
    "energy":0.703,
    "key":10,
    "loudness":-7.951,
    "mode":0,
    "speechiness":0.306,
    "acousticness":0.206,
    "instrumentalness":0.0,

In [15]:
# Guardar el JSON en un archivo
with open('music_data.json', 'w') as f:
    f.write(json_data)

print("Archivo guardado como 'music_data.json'")

Archivo guardado como 'music_data.json'

In [16]:
# Cargar el JSON para verificar
with open('music_data.json', 'r') as f:
    loaded_json = json.load(f)

# Mostrar el primer registro del JSON cargado
print("Primer registro del JSON:")
print(json.dumps(loaded_json[0], indent=2))

Primer registro del JSON:
{
  "danceability": 0.803,
  "energy": 0.624,
  "key": 7,
  "loudness": -6.764,
  "mode": 0,
  "speechiness": 0.0477,
  "acousticness": 0.451,
  "instrumentalness": 0.000734,
  "liveness": 0.1,
  "valence": 0.628,
  "tempo": 95.968,
  "duration_ms": 304524,
  "time_signature": 4,
  "liked": 0
}

In [24]:
# 1. Verificar valores nulos
print("\nValores nulos por columna:")
print(df.isnull().sum())

# 2. Verificar tipos de datos
print("\nTipos de datos:")
print(df.dtypes)

Valores nulos por columna:
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
duration_ms         0
time_signature      0
liked               0
dtype: int64

Tipos de datos:
danceability        float64
energy              float64
key                   int64
loudness            float64
mode                  int64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
tempo               float64
duration_ms           int64
time_signature        int64
liked                 int64
dtype: object

In [17]:
# Instalar psycopg2 (adaptador PostgreSQL para Python)
!pip install psycopg2-binary

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.10-cp313-cp313-win_amd64.whl.metadata (4.8 kB)
Downloading psycopg2_binary-2.9.10-cp313-cp313-win_amd64.whl (2.6 MB)
   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.6 MB ? eta -:--:--
   -------------------------------- ------- 2.1/2.6 MB 8.4 MB/s eta 0:00:01
   ---------------------------------------- 2.6/2.6 MB 8.1 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.10

[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [18]:
import psycopg2
from psycopg2 import sql
import pandas as pd
import json

In [19]:
# Configura tus parámetros de conexión
db_params = {
    'host': 'localhost', 
    'database': 'musica',
    'user': 'postgres',
    'password': '1234',
    'port': '5432'  # Puerto por defecto de PostgreSQL
}

In [20]:
def connect_to_db():
    try:
        # Establecer conexión
        conn = psycopg2.connect(**db_params)
        print("Conexión exitosa a PostgreSQL")
        return conn
    except Exception as e:
        print(f"Error al conectar a PostgreSQL: {e}")
        return None

In [21]:
def create_table(conn):
    try:
        cursor = conn.cursor()
        
        create_table_query = """
        CREATE TABLE IF NOT EXISTS music_features (
            id SERIAL PRIMARY KEY,
            danceability FLOAT,
            energy FLOAT,
            key INT,
            loudness FLOAT,
            mode INT,
            speechiness FLOAT,
            acousticness FLOAT,
            instrumentalness FLOAT,
            liveness FLOAT,
            valence FLOAT,
            tempo FLOAT,
            duration_ms INT,
            time_signature INT,
            liked INT
        )
        """
        cursor.execute(create_table_query)
        conn.commit()
        print("Tabla creada exitosamente")
    except Exception as e:
        print(f"Error al crear tabla: {e}")
    finally:
        if cursor:
            cursor.close()

In [22]:
def insert_data_from_json(conn, json_file_path):
    try:
        # Cargar el archivo JSON
        with open(json_file_path, 'r') as f:
            data = json.load(f)
        
        cursor = conn.cursor()
        
        # Preparar consulta de inserción
        insert_query = """
        INSERT INTO music_features (
            danceability, energy, key, loudness, mode, speechiness,
            acousticness, instrumentalness, liveness, valence, tempo,
            duration_ms, time_signature, liked
        ) VALUES (
            %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
        )
        """
        
        # Insertar cada registro
        for record in data:
            cursor.execute(insert_query, (
                record['danceability'],
                record['energy'],
                record['key'],
                record['loudness'],
                record['mode'],
                record['speechiness'],
                record['acousticness'],
                record['instrumentalness'],
                record['liveness'],
                record['valence'],
                record['tempo'],
                record['duration_ms'],
                record['time_signature'],
                record['liked']
            ))
        
        conn.commit()
        print(f"{len(data)} registros insertados exitosamente")
    except Exception as e:
        conn.rollback()
        print(f"Error al insertar datos: {e}")
    finally:
        if cursor:
            cursor.close()

In [23]:
# Establecer conexión
conn = connect_to_db()

if conn:
    try:
        # Crear tabla
        create_table(conn)
        
        # Insertar datos (asegúrate de que el archivo JSON existe)
        insert_data_from_json(conn, 'music_data.json')
        
        # Opcional: Leer datos desde PostgreSQL a un DataFrame
        query = "SELECT * FROM music_features LIMIT 5"
        df_from_db = pd.read_sql(query, conn)
        print("\nPrimeros 5 registros desde PostgreSQL:")
        print(df_from_db)
        
    finally:
        # Cerrar conexión
        conn.close()
        print("\nConexión cerrada")

Conexión exitosa a PostgreSQL
Tabla creada exitosamente
195 registros insertados exitosamente

Primeros 5 registros desde PostgreSQL:
   id  danceability  energy  key  loudness  mode  speechiness  acousticness  \
0   1         0.803  0.6240    7    -6.764     0       0.0477         0.451
1   2         0.762  0.7030   10    -7.951     0       0.3060         0.206
2   3         0.261  0.0149    1   -27.528     1       0.0419         0.992
3   4         0.722  0.7360    3    -6.994     0       0.0585         0.431
4   5         0.787  0.5720    1    -7.516     1       0.2220         0.145

   instrumentalness  liveness  valence    tempo  duration_ms  time_signature  \
0          0.000734    0.1000   0.6280   95.968       304524               4
1          0.000000    0.0912   0.5190  151.329       247178               4
2          0.897000    0.1020   0.0382   75.296       286987               4
3          0.000001    0.1230   0.5820   89.860       208920               4
4          0.000000    0.0753   0.6470  155.117       179413               4

   liked
0      0
1      1
2      0
3      1
4      1

Conexión cerrada

C:\Users\LAPTO\AppData\Local\Temp\ipykernel_35932\2147416623.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_from_db = pd.read_sql(query, conn)